services:
  - type: web
    name: cosmetics-backend
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000